insert into public.motivation_tips (category,text) values
('motivation','Jeder Satz, den ihr heute sauber macht, ist ein Versprechen an euer zukünftiges Ich. David & Svenja, ihr baut euch gerade selbst.'),
('motivation','Es ist nie das eine große Workout, das euch verändert – es sind die hundert, die ihr trotzdem durchzieht.'),
('motivation','Ihr müsst heute nicht euer bestes Training abliefern. Ihr müsst nur auftauchen und sauber arbeiten.'),
('motivation','Stell dir vor, wie gut sich das Duschen nach dem Training anfühlt. Genau dafür gehst du jetzt los.'),
('motivation','Zusammen trainieren heißt: Wenn einer schwächelt, zieht der andere mit. Nutzt das.'),
('motivation','Der Hantel ist es egal, wie du dich fühlst. Sie belohnt nur, dass du da bist.'),
('motivation','Motivation bringt dich ins Studio, Gewohnheit hält dich drin. Baue heute an der Gewohnheit.'),
('motivation','Ein mittelmäßiges Training, das stattfindet, schlägt jedes perfekte, das nur im Kopf existiert.'),
('motivation','Denk nicht an alle Sätze. Denk nur an den nächsten – und der ist machbar.'),
('motivation','Heute investierst du in einen Körper, der dich noch in 30 Jahren tragen soll. Gute Anlage.'),
('motivation','Die schwersten Schritte sind die zur Hantelbank. Danach läuft es fast von allein.'),
('motivation','Du wirst dieses Training nie bereuen. Diesen Satz hat noch niemand falsch gefunden.'),
('motivation','Macht es zu eurem Ritual: kein perfekter Tag, sondern ein gemeinsamer. Das hält länger als jede Hochphase.'),
('motivation','Der Körper schreit am Anfang, doch nach dem dritten Satz ist die Stimme leiser. Bleib dran.'),
('motivation','Stark werden ist langweilig: dieselben Übungen, ein bisschen mehr. Genau diese Langeweile bringt Ergebnisse.'),
('motivation','Du musst die Hantel nicht lieben. Du musst nur regelmäßig mit ihr Zeit verbringen.'),
('motivation','Wer heute schwitzt, schaut morgen im Spiegel zufriedener zurück. Kleine Münze, große Rendite.'),
('motivation','Ihr seid kein Einzelkämpfer-Projekt. Feiert die kleinen Fortschritte des anderen lauter als die eigenen.'),
('motivation','Niemand wurde je schwächer davon, dass er ins Studio gegangen ist. Schlimmstenfalls war es ein guter Tag.'),
('motivation','Die Couch ist schon gewonnen worden – millionenfach. Geh heute den anderen Weg.'),
('motivation','Erfolg ist die Summe kleiner Wiederholungen, jeden Tag dasselbe getan. Genau das macht ihr.'),
('motivation','Du kannst stolz auf dich sein, sobald du die Trainingstasche packst. Der Rest ist Bonus.'),
('motivation','Frag dich nicht, ob du Lust hast. Frag dich, wer du in einem Jahr sein willst.'),
('motivation','Das Gewicht von letzter Woche ist heute dein Aufwärmsatz. So fühlt sich Fortschritt an.'),
('motivation','Trainiert füreinander: David zählt für Svenja mit, Svenja feuert David an. Geteilte Last ist halbe Last.'),
('motivation','Es gibt keinen perfekten Zeitpunkt zum Anfangen. Es gibt nur jetzt und sauber.'),
('motivation','Jede Wiederholung ist eine kleine Abstimmung mit dir selbst: Ich gebe nicht auf.'),
('motivation','Du baust nicht nur Muskeln, du baust Selbstvertrauen. Beides wächst unter Spannung.'),
('motivation','Heute ein bisschen besser als gestern – mehr verlangt niemand von dir.'),
('motivation','Der größte Sieg des Tages kann sein, einfach hingegangen zu sein. Nimm ihn mit.'),
('motivation','Ihr trainiert nicht gegeneinander, sondern Seite an Seite gegen das Aufgeben. Starkes Team.'),
('motivation','Manche Tage trägt dich die Energie, andere die Disziplin. Beide bringen dich ans Ziel.'),
('motivation','Denk an das Gefühl nach dem letzten Satz, nicht an die Mühe davor. Das zieht dich durch.'),
('motivation','Du wirst nie alle deine Ziele an einem Tag erreichen – aber an keinem ohne diesen einen.'),
('technik','Pack die Hantel fest, als würdest du sie zerdrücken wollen. Fester Griff, sicherer Körper, mehr Kraft.'),
('technik','Geh bewusst in die gedehnte Position – dort wächst der Muskel am meisten. Spannung halten, nicht fallen lassen.'),
('technik','Die exzentrische Phase ist kein Pausenknopf: Lass das Gewicht über drei Sekunden kontrolliert herab.'),
('technik','Mind-Muscle-Connection: Spüre den Zielmuskel arbeiten, bevor du das Gewicht überhaupt bewegst.'),
('technik','Volle Range of Motion schlägt mehr Gewicht. Lieber sauber tief als schwer und halb.'),
('technik','Du dominierst das Gewicht – nie umgekehrt. Wenn die Hantel dich führt, ist sie zu schwer.'),
('technik','Lege die Last nie auf den Sehnen ab. Halte den Muskel unter konstanter Spannung, auch am Umkehrpunkt.'),
('technik','Erzeuge die Spannung bewusst, bevor du startest: Körper anspannen, dann erst bewegen.'),
('technik','Atme an der schwersten Stelle aus. Kontrollierte Atmung bedeutet kontrollierte Bewegung.'),
('technik','Beim Drücken den Boden mit den Füßen wegschieben – Kraft beginnt von unten.'),
('technik','Wenn du die Wiederholung nicht beschreiben könntest, war sie zu schnell. Verlangsame die Negative.'),
('technik','Die letzten Zentimeter der Dehnung sind kein Risiko, wenn du sie kontrollierst – sie sind dein Gold.'),
('technik','Ein sauberer Satz mit Fokus ist mehr wert als drei mit Schwung. Qualität schlägt Quantität.'),
('technik','Stell dir vor, dein Zielmuskel zieht das Gewicht, nicht deine Gelenke. Das ist Mind-Muscle-Connection.'),
('technik','Halte die Schulterblätter zusammen und unten, bevor du drückst. Stabiles Fundament, gesunde Schulter.'),
('technik','Kein Reißen, kein Werfen: Wenn du die Hantel kontrollierst, kontrollierst du das Ergebnis.'),
('technik','Spür die Dehnung am unteren Punkt, halte kurz die Spannung – dann bewusst zurück.'),
('technik','Die Bewegung beginnt im Kopf: Visualisiere den Muskel, dann zieht er auch mit.'),
('technik','Volle ROM heißt nicht durchschnappen. Geh tief, aber bleib im aktiven Spannungsbereich.'),
('technik','Wenn du am Endpunkt entspannst, verlierst du den Reiz. Bleib unter Last, von Anfang bis Ende.'),
('technik','Langsam ablassen ist die halbe Miete: Die Negative baut genauso viel Muskel wie das Drücken.'),
('technik','Fester Stand, fester Griff, fester Kern. Drei Anker, dann erst die Wiederholung.'),
('technik','Frag dich bei jedem Satz: Führe ich das Gewicht oder folgt es mir? Es soll dir folgen.'),
('technik','Tempo macht Technik: 1 Sekunde hoch, kurz halten, 3 Sekunden runter. Probiert es heute aus.'),
('technik','Ziehe mit dem Ellenbogen, nicht mit der Hand – so triffst du den Rücken statt den Unterarm.'),
('technik','Die saubere Ausführung schützt deine Gelenke heute und deine Form in zehn Jahren.'),
('technik','In die Dehnung gehen heißt mutig sein, nicht leichtsinnig. Kontrolliert tief, nie ruckartig.'),
('technik','Spann den Muskel an, bevor das Gewicht sich bewegt – Vorspannung verhindert Schwung.'),
('technik','Wenn der Nacken bei Übungen mitarbeitet, stimmt die Technik nicht. Schultern weg von den Ohren.'),
('technik','Greif fest zu, aber verkrampf nicht. Stabilität im Handgelenk, Lockerheit im Schultergürtel.'),
('technik','Jede Wiederholung verdient denselben Fokus wie die erste. Müdigkeit ist keine Ausrede für schlampige Form.'),
('technik','Kontrolliere den Umkehrpunkt aktiv. Dort entscheidet sich, ob Muskel oder Schwung arbeitet.'),
('progression','Dynamic Double Progression: Bist du oben in der Rep-Range bei allen Sätzen, erhöhst du beim nächsten Mal das Gewicht.'),
('progression','Erst Wiederholungen aufbauen, dann Gewicht. Schritt für Schritt nach oben statt großer Sprünge.'),
('progression','Heute eine saubere Wiederholung mehr als letztes Mal – das ist messbarer Fortschritt.'),
('progression','Wenn du das obere Ende der Range knackst, hast du dir die nächste Gewichtsstufe verdient.'),
('progression','Fortschritt heißt stetige Verbesserung unter gleichen Bedingungen, nicht ständiger Übungswechsel.'),
('progression','Notiere jeden Satz. Was du misst, kannst du steigern – und du wirst die Kurve nach oben sehen.'),
('progression','Kleine Sprünge halten den Reiz: 2,5 kg mehr sind langfristig stärker als ein riskanter Doppelschritt.'),
('progression','Bleib bei der Übung, bis sie dir wirklich gehört. Wechsel sind kein Fortschritt, sondern oft eine Flucht.'),
('progression','Stagnation ist kein Scheitern, sondern ein Signal: gleiches Gewicht, eine Wiederholung mehr anpeilen.'),
('progression','Double Progression heißt geduldig sein: erst die Reps voll machen, dann erst schwerer werden.'),
('progression','Vergleiche dich nur mit deinem letzten Trainingslog – das ist der einzige faire Gegner.'),
('progression','Gleicher Aufbau, gleiche Reihenfolge, gleiche Pausen: Nur unter konstanten Bedingungen zählt Fortschritt wirklich.'),
('progression','Eine zusätzliche saubere Wiederholung ist Wachstum. Sammle sie geduldig, sie summieren sich zu Kraft.'),
('progression','Wenn du noch nicht oben in der Range bist, ist heute kein Tag fürs Steigern – sondern fürs Wiederholungen-Sammeln.'),
('progression','Trau dich, das Gewicht zu erhöhen, wenn die Range voll ist. Wer nie steigert, bleibt stehen.'),
('progression','Lieber langsam und stetig wachsen als schnell und verletzt pausieren. Die Doppelprogression belohnt Geduld.'),
('progression','Dein Trainingslog ist deine Landkarte. Ohne sie raten David & Svenja nur, mit ihr wisst ihr es.'),
('progression','Jede neue Gewichtsstufe darf sich erst ungewohnt anfühlen. Bleib dran, die Reps kommen zurück.'),
('progression','Fortschritt ist selten linear. Ein Plateau heißt: Geduld halten, Bedingungen konstant halten, weitermachen.'),
('progression','Erhöhst du das Gewicht, fängst du wieder am unteren Ende der Rep-Range an. Das ist Plan, kein Rückschritt.'),
('progression','Die schönste Zahl im Log ist die, die letztes Mal nicht da war – eine Wiederholung mehr.'),
('progression','Wechsle nicht ständig den Plan. Demselben Reiz konsequent ausgesetzt zu sein, ist der Reiz.'),
('progression','Bei der Doppelprogression bist du nie planlos: Reps rauf bis zum Limit, dann Gewicht rauf.'),
('progression','Wenn beide Sätze die obere Grenze treffen, ist das Gewicht reif für die nächste Stufe. Glückwunsch.'),
('progression','Vertrau dem System: Kleine, konsistente Steigerungen schlagen jeden spektakulären Maximalversuch.'),
('progression','Bleib bei deinen Kernübungen, bis sie dich langweilen – genau dann zahlen sie am meisten aus.'),
('progression','Ein halbes Kilo mehr klingt nach nichts. Über ein Jahr ist es ein völlig anderer Körper.'),
('progression','Reps am unteren Rand der Range? Heute hältst du das Gewicht und arbeitest nach oben. Geduld zahlt sich aus.'),
('progression','Steigere erst, wenn die Technik bei voller Range sitzt. Sauber zuerst, schwer danach.'),
('progression','Gemeinsam Logs vergleichen: Wo war David vor vier Wochen, wo ist Svenja heute? Sichtbarer Beweis eurer Arbeit.'),
('ernaehrung','Genug Protein ist der Baustoff für jeden Muskel, den ihr im Studio reizt. Zielt auf rund 1,6-2,2 g pro kg Körpergewicht.'),
('ernaehrung','Verteile dein Protein über den Tag: Vier Portionen sättigen den Muskel besser als eine große.'),
('ernaehrung','Trinken nicht vergessen: Schon leichter Flüssigkeitsmangel kostet dich Kraft und Konzentration im Training.'),
('ernaehrung','Muskeln wachsen am Esstisch, nicht nur an der Hantel. Iss genug, um den Aufbau zu ermöglichen.'),
('ernaehrung','Ein Glas Wasser vor jedem Satz Pause klingt simpel, hält dich aber leistungsfähig. Flasche immer dabei.'),
('ernaehrung','Kohlenhydrate sind kein Feind, sondern dein Treibstoff. Fülle die Speicher für ein kraftvolles Workout.'),
('ernaehrung','Wer aufbauen will, braucht einen leichten Kalorienüberschuss. Zu wenig essen bremst eure harte Arbeit aus.'),
('ernaehrung','Eiweiß zu jeder Hauptmahlzeit: Quark, Eier, Hähnchen, Linsen – sucht euch eure Favoriten als Paar.'),
('ernaehrung','Dein Durstgefühl hinkt hinterher. Trink über den Tag verteilt, nicht erst, wenn die Kehle trocken ist.'),
('ernaehrung','Eine proteinreiche Mahlzeit nach dem Training schließt das Fenster, das ihr gerade aufgerissen habt.'),
('ernaehrung','Iss echtes Essen zuerst, Shakes als Ergänzung. Vollwertig schlägt fast immer das Pulver.'),
('ernaehrung','Plant eure Mahlzeiten als Paar vor. Wer vorbereitet ist, isst zielgerichtet statt zufällig.'),
('ernaehrung','Genug Wasser unterstützt Gelenke, Muskeln und Herz. Gerade bei Herz-Themen ist gute Flüssigkeitszufuhr wichtig.'),
('ernaehrung','Kein perfektes Essen nötig – ein konstant gutes reicht. Eiweiß, Gemüse, genug Kalorien, jeden Tag.'),
('ernaehrung','Protein sättigt und schützt die Muskeln. Es ist die wichtigste Stellschraube, egal ob Auf- oder Abbau.'),
('ernaehrung','Salz und Elektrolyte nicht vergessen, wenn ihr stark schwitzt – das hält Kreislauf und Pumpe stabil.'),
('ernaehrung','Ein guter Tag in der Küche macht euer Training wertvoller. Esst, als wäre Regeneration euer zweites Workout.'),
('ernaehrung','Trinkt schon vor dem Training ausreichend. Gut hydriert startet ihr stärker in den ersten Satz.'),
('ernaehrung','Nicht hungern, um schneller schlank zu werden. Crash-Diäten kosten Muskeln, die ihr euch hart erarbeitet habt.'),
('ernaehrung','Eine Handvoll Protein, eine Faust Gemüse, eine Handvoll Kohlenhydrate – simple Faustregel pro Mahlzeit.'),
('ernaehrung','Koffein vor dem Training kann pushen – aber bei Herz-Extrasystolen lieber maßvoll und vom Arzt abgesegnet.'),
('ernaehrung','Esst genug, um stark zu sein, nicht nur, um satt zu sein. Leistung beginnt auf dem Teller.'),
('ernaehrung','Stellt euch abends eine gefüllte Wasserflasche bereit. Hydration startet, bevor ihr aus dem Bett seid.'),
('ernaehrung','Proteinreiches Frühstück setzt den Ton für den Tag und schützt eure Muskeln von der ersten Stunde an.'),
('regeneration','Muskeln wachsen im Schlaf, nicht im Studio. Sieben bis neun Stunden sind euer wichtigstes Aufbau-Supplement.'),
('regeneration','Ein Deload ist kein Rückschritt, sondern ein Anlauf. Plant alle paar Wochen eine leichtere Woche ein.'),
('regeneration','Schmerz ist kein Trainingsziel. Trainiert bis zum echten Versagen, aber stoppt vor jeder drohenden Verletzung.'),
('regeneration','Pausen zwischen den Sätzen sind kein Zeitverlust, sondern eure Vorbereitung auf einen starken nächsten Satz.'),
('regeneration','Ein Ruhetag ist Teil des Plans, nicht das Gegenteil davon. Erholung ist, wo der Fortschritt entsteht.'),
('regeneration','Höre auf deinen Körper: Stechen in Gelenken oder Sehnen ist ein Stoppschild, kein Ehrenabzeichen.'),
('regeneration','David, bei Herz-Extrasystolen gilt: Belastung dosieren, auf Signale achten und im Zweifel ärztlich abklären.'),
('regeneration','Svenja, schütze deine HWS und Knie – wärm dich gründlich auf und meide ruckartige Lasten auf den Gelenken.'),
('regeneration','Guter Schlaf schlägt jedes Pre-Workout. Geht heute eine halbe Stunde früher ins Bett, eurem Muskel zuliebe.'),
('regeneration','Versagen sauber erreichen heißt: Die letzte Wiederholung scheitert an der Kraft, nicht an der Form.'),
('regeneration','Wer ständig erschöpft trainiert, baut ab statt auf. Erkennt Übermüdung und gönnt euch den nötigen Reset.'),
('regeneration','Ein leichter Spaziergang an Ruhetagen fördert die Durchblutung und beschleunigt eure Erholung.'),
('regeneration','Schmerz, der bleibt, gehört zum Arzt – nicht zum nächsten Satz. Verletzungen vermeiden hat immer Vorrang.'),
('regeneration','Aufwärmen ist kein optionales Extra. Zwei lockere Sätze schützen Gelenke und holen mehr Leistung heraus.'),
('regeneration','Nimm dir nach dem Training Zeit zum Runterkommen – gerade bei Herz-Themen ist sanftes Auslaufen klug.'),
('regeneration','Schlaf, Wasser, Ruhe: Diese drei kostenlosen Werkzeuge bringen oft mehr als jedes teure Supplement.'),
('regeneration','Ein Deload bedeutet weniger Gewicht oder Sätze, nicht weniger Disziplin. Plant ihn bewusst, nicht aus Frust.'),
('regeneration','Volle Pausen geben dem Nervensystem Zeit. Eile zwischen den Sätzen kostet Kraft und Sicherheit.'),
('regeneration','Hör zu, wenn dein Körper flüstert, damit er nie schreien muss. Frühe Signale ernst nehmen spart Wochen Pause.'),
('regeneration','Bei HWS-Problemen: Nacken neutral halten, kein Überstrecken. Eine stabile Kopfposition schützt die Halswirbelsäule.'),
('regeneration','Knie sicher führen: Knie folgen der Fußspitze, keine einknickenden Bewegungen unter Last. Svenja, achte darauf.'),
('regeneration','Lieber einen Satz weniger als eine Verletzung mehr. Langfristigkeit schlägt jedes kurzfristige Egotraining.'),
('regeneration','Erholung ist aktiv geplant, nicht zufällig. Wer Pausen ernst nimmt, trainiert die nächste Einheit stärker.'),
('regeneration','Müde, aber gesund? Trainiere reduziert. Krank oder verletzt? Ruhe heute, gewinne langfristig.'),
('regeneration','Dehnen und lockere Mobilität halten eure Gelenke geschmeidig – besonders Nacken und Knie danken es euch.'),
('regeneration','Echtes Versagen heißt: Du kannst keine saubere Wiederholung mehr, nicht keine wackelige mehr. Kenne den Unterschied.'),
('mindset','Disziplin ist, das Richtige zu tun, auch wenn die Lust fehlt. Sie trägt euch weiter als jede Motivation.'),
('mindset','Konstanz schlägt Intensität. Drei solide Jahre besiegen drei spektakuläre Wochen mit Abbruch.'),
('mindset','Geduld ist ein Trainingsmuskel. Je öfter ihr ihn einsetzt, desto stärker tragt ihr Plateaus.'),
('mindset','Fortschritt ist leise und langsam. Vertraut dem Prozess, auch wenn der Spiegel mal schweigt.'),
('mindset','Vergleicht euch nicht mit anderen im Studio. Euer einziger Maßstab ist euer letztes Training.'),
('mindset','Ein verpasstes Training ist ein Ausrutscher, zwei sind eine Entscheidung. Kehrt sofort zurück zur Routine.'),
('mindset','Du wirst nie an einen Punkt kommen, an dem es immer leicht ist. Stark zu sein heißt, trotzdem zu kommen.'),
('mindset','Setzt auf Systeme, nicht auf Stimmungen. Ein fester Plan trägt euch durch unmotivierte Tage.'),
('mindset','Wer ständig den Plan wechselt, erntet nie. Bleibt lange genug, um den Fortschritt sehen zu können.'),
('mindset','Identität schlägt Willenskraft: Ihr seid Menschen, die trainieren. Das macht jede Entscheidung leichter.'),
('mindset','Schlechte Tage gehören dazu. Ein durchschnittliches Training ist trotzdem ein Schritt nach vorn.'),
('mindset','Die Geduld, ein Kilo nach dem anderen zu steigern, ist genau die Geduld, die euch ans Ziel bringt.'),
('mindset','Erfolg ist langweilig: aufstehen, trainieren, essen, schlafen, wiederholen. Liebt die Wiederholung.'),
('mindset','Vergiss Perfektion, ziele auf Konsistenz. Niemand baut einen Körper an einem heroischen Tag.'),
('mindset','Als Paar haltet ihr euch gegenseitig im Spiel. Verantwortung füreinander ist die stärkste Disziplin.'),
('mindset','Das Plateau ist kein Feind, sondern eine Prüfung der Geduld. Bestanden wird sie durch Dranbleiben.'),
('mindset','Frag dich nicht, ob es heute Spaß macht. Frag dich, ob das künftige Ich dir danken wird.'),
('mindset','Kleine, konsequente Schritte schlagen große, sporadische Sprünge. Das gilt im Studio wie im Leben.'),
('mindset','Du verlierst nicht, wenn du langsam bist. Du verlierst nur, wenn du ganz aufhörst.'),
('mindset','Macht das Training so klein, dass ihr nicht Nein sagen könnt. Angefangen ist halb gewonnen.'),
('mindset','Disziplin heute ist Freiheit morgen: ein Körper, der mitmacht, statt euch zu bremsen.'),
('mindset','Misst eure Fortschritte über Monate, nicht Tage. Die Tageslaune lügt, das Trainingslog nicht.'),
('mindset','Wer Bedingungen konstant hält und geduldig bleibt, wird vom Fortschritt fast schon zwangsläufig belohnt.'),
('mindset','Motivation ist ein Gast, Disziplin ein Mitbewohner. Verlasst euch auf den, der immer da ist.'),
('mindset','Ihr müsst nicht jeden Tag stark sein – nur öfter dranbleiben als aufgeben. Das reicht völlig.'),
('mindset','Vertrau dem langen Spiel. In einem Jahr ist heute nur ein winziger, aber unverzichtbarer Punkt auf der Kurve.'),
('motivation','Du hast schon den schwersten Teil hinter dir, wenn du diese App geöffnet hast. Jetzt nur noch trainieren.'),
('motivation','Stell dir das gute Gefühl vor, heute den Haken hinter das Training zu setzen. Holt es euch.'),
('technik','Halte am tiefsten Punkt eine Sekunde inne. Diese bewusste Spannung trennt Training von bloßem Bewegen.'),
('technik','Wenn du das Gewicht spürst statt nur bewegst, arbeitest du richtig. Fühlen schlägt zählen.'),
('technik','Stabilisiere zuerst, bewege dann. Ein ruhiger Rumpf macht jede Wiederholung sicherer und stärker.'),
('progression','Heute knapp die Range verfehlt? Kein Drama – beim nächsten Mal holst du die fehlende Wiederholung.'),
('progression','Gleiche Übung, gleiche Technik, mehr Leistung über die Zeit: Das ist das ganze Geheimnis des Aufbaus.'),
('ernaehrung','Frag dich vor jeder Mahlzeit: Wo ist mein Protein? Dann steht das Wichtigste schon fest.'),
('ernaehrung','Trinken über den Tag verteilt hält Kreislauf und Kopf stabil – wichtiger als jeder hektische Schluck im Training.'),
('regeneration','Wenn der Schlaf schlecht war, reduziert die Last statt durchzubeißen. Klug pausieren ist auch trainieren.'),
('regeneration','Achtet auf eure Herzfrequenz und euren Atem. Trainieren soll fordern, nicht in Atemnot oder Schwindel kippen.'),
('mindset','Vergleicht euch mit dem, der ihr letztes Jahr wart. An diesem Maßstab gewinnt ihr garantiert.'),
('mindset','Jeder Profi war einmal Anfänger, der einfach nicht aufgehört hat. Genau das tut ihr gerade.'),
('motivation','Das Training, vor dem du dich am meisten drückst, ist oft das, nach dem du dich am besten fühlst.'),
('technik','Beim Senken kommandierst du das Gewicht, nicht die Schwerkraft. Bremse bewusst, dort liegt halber Muskelreiz.'),
('technik','Zieh die Schultern nie hoch zu den Ohren. Schultern tief und stabil schützt Nacken und Halswirbelsäule.'),
('progression','Wenn das Gewicht heute leichter wirkt als letzte Woche, ist das kein Zufall – das ist eure Arbeit.'),
('progression','Steigere nur, wenn alle Arbeitssätze die obere Rep-Grenze sauber erreichen. Halb gilt nicht, ganz zählt.'),
('ernaehrung','Genug essen ist Mut, nicht Maßlosigkeit. Ohne Bausteine bleibt der Trainingsreiz wirkungslos.'),
('regeneration','Ein Tag ohne Training ist kein verlorener Tag, wenn er euch für drei starke Einheiten erholt.'),
('mindset','Die besten Ergebnisse kommen aus der langweiligen Konstanz, die andere vorzeitig aufgeben. Bleibt langweilig konsequent.'),
('ernaehrung','Plant Protein wie ein Training: feste Portionen, feste Zeiten. Struktur macht aus Vorsatz Gewohnheit.'),
('regeneration','Stechen ist anders als Brennen. Brennen ist Arbeit, Stechen ist Warnung – höre auf den Unterschied.'),
('mindset','Ihr seid kein Sprint, ihr seid ein Marathon zu zweit. Teilt euch die Kräfte und kommt gemeinsam an.'),
('ernaehrung','Halte deine Wasserflasche in Sichtweite. Was du siehst, trinkst du eher – simpel, aber wirksam.'),
('regeneration','Nach hartem Training braucht der Körper Ruhe, nicht noch mehr Reiz. Mehr ist nicht immer besser.'),
('mindset','Disziplin ist die Brücke zwischen euren Zielen und der Realität. Heute legt ihr wieder eine Planke.'),
('ernaehrung','Eiweiß baut, Wasser transportiert, Kalorien liefern Energie. Ohne diese drei läuft kein Aufbau rund.');
